apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-service.fullname" . }}-config
  labels:
    {{- include "api-service.labels" . | nindent 4 }}
    {{- include "api-service.selectorLabels" . | nindent 4 }}
data:
  PORT: {{ .Values.service.port | quote }}
  ENDPOINTS: {{ join "," .Values.service.endpoints | quote }}
