apiVersion: v1
kind: Secret
metadata:
  name: {{ include "classroom-service.fullname" . }}-postgres-secret
  labels:
    {{- include "classroom-service.labels" . | nindent 4 }}
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  POSTGRES_DB: {{ default "users" .Values.postgres.dbName | b64enc }}
  POSTGRES_USER: {{ .Values.postgres.user | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | b64enc }}
