apiVersion: v1
kind: Service
metadata:
  name: {{ include "classroom-service.fullname" . }}-postgres
  labels:
    {{- include "classroom-service.labels" . | nindent 4 }}
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    {{- include "classroom-service.labels" . | nindent 4 }}
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
