apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-service.fullname" . }}-config
  labels:
    {{- include "api-service.labels" . | nindent 4 }}
    {{- include "api-service.selectorLabels" . | nindent 4 }}
data:
  PORT: {{ .Values.service.port | quote }}
  NUXT_PUBLIC_API_BASE: {{ .Values.service.userApiBaseUrl | quote }}
  NUXT_PUBLIC_API_BASE_MESSAGING: {{ .Values.service.messagingApiBaseUrl | quote }}
  NUXT_PUBLIC_API_BASE_CLASSROOM: {{ .Values.service.classroomApiBaseUrl | quote }}
  NUXT_PUBLIC_API_BASE_SCHEDULE: {{ .Values.service.scheduleApiBaseUrl | quote }}
