apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-service.fullname" . }}-config
  labels:
    {{- include "api-service.labels" . | nindent 4 }}
    {{- include "api-service.selectorLabels" . | nindent 4 }}
data:
  PORT: {{ .Values.service.port | quote }}
  API_BASE_URL_USER: {{ .Values.service.userApiBaseUrl | quote }}
  API_BASE_URL_MESSAGING: {{ .Values.service.messagingApiBaseUrl | quote }}
  API_BASE_URL_CLASSROOM: {{ .Values.service.classroomApiBaseUrl | quote }}
  API_BASE_URL_SCHEDULE: {{ .Values.service.scheduleApiBaseUrl | quote }}
