apiVersion: v1
kind: Service
metadata:
  name: {{ include "messaging-service.fullname" . }}
  labels:
    {{- include "messaging-service.labels" . | nindent 4 }}
    {{- include "messaging-service.selectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "messaging-service.selectorLabels" . | nindent 4 }}
