apiVersion: v1
kind: Secret
metadata:
  name: {{ include "user-service.fullname" . }}-secret
  labels:
    {{- include "user-service.labels" . | nindent 4 }}
    {{- include "user-service.selectorLabels" . | nindent 4 }}
data:
  DATABASE_URL: {{ printf "postgresql://%s:%s@%s/%s?schema=%s" .Values.postgres.user .Values.postgres.password (printf "%s-postgres" (include "user-service.fullname" .)) (default "users" .Values.postgres.dbName) (default "public" .Values.postgres.schema) | b64enc}}
  JWT_SECRET: {{ .Values.jwtSecret | b64enc }}
  COOKIE_SECRET: {{ .Values.cookieSecret | b64enc }}
  GITHUB_CLIENT_ID: {{ .Values.oidc.githubClientId | b64enc }}
  GITHUB_CLIENT_SECRET: {{ .Values.oidc.githubClientSecret | b64enc }}
