apiVersion: v1
kind: Service
metadata:
  name: {{ include "schedule-service.fullname" . }}
  labels:
    {{- include "schedule-service.labels" . | nindent 4 }}
    {{- include "schedule-service.selectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "schedule-service.selectorLabels" . | nindent 4 }}
